name: Build and deploy JAR app to Azure Web App - inmoapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Rename JAR to app.jar
        run: |
          mkdir -p deploy
          cp target/*.jar deploy/app.jar
          ls -la deploy/

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: deploy/app.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: .

      - name: Verify JAR exists
        run: |
          echo "Verifying JAR in workspace:"
          ls -la

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E65FF4176A1E4FDBAA825128B0F57B83 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3F53007499DA48449D94358198A741AF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A83EBDAC1CA143D1B6DAE49BED031A8B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'inmoapi'
          slot-name: 'Production'
          package: './app.jar'



